### ISSUE TITLE
Upload latest version to Hackage

### ISSUE THREAD

**Issue by benjamin-hodgson** [ekmett/bound#32]
The version of `bound` on Hackage, `1.0.7`, supports only `transformers<0.5`. This is causing me trouble when installing `bound` with a fresh install of the latest Haskell Platform, [which comes with `transformers-0.5.2.0`](https://www.haskell.org/platform/contents.html).

I see from the Cabal file in this repo that the dependency has already been updated - could you please upload the latest version to Hackage?

Thanks!

**Comment by slpopejoy** [comment]
Bump

**Comment by sjakobi** [comment]
The `binary < 0.8` bound is problematic too, as [this stackoverflow user](http://stackoverflow.com/questions/40750759/haskell-stack-exception-missing-dependencies) experienced.

If there is any work to be done before a new version can be released, please point that out, so others can pick up the slack! :)

**Comment by phadej** [comment]
Have to go thru all examples & haddocks and check that they are up to date. Will do today.

I'm not aware if there is some (possibly private) downstream issues @ekmett want to be sorted out first.

**Comment by phadej** [comment]
I went thru examples and haddocks, there shouldn't be any `Prelude.Extras` mentions (`grep` agrees).

AFAICS there isn't anything blocking the release, is there?

**Comment by ollef** [comment]
Is this what's stopping bound from being on Stackage LTS?

**Comment by sjakobi** [comment]
> Is this what's stopping bound from being on Stackage LTS?

Yes, although there are [quite a few dependencies](http://packdeps.haskellers.com/feed?needle=exact%3Abound) that need bumping by now. 

@ekmett: Please consider getting a co-maintainer for this package. I'm sure there'll be some volunteers. (I don't know this package well enough though.)

**Comment by slpopejoy** [comment]
Also, are there significant/breaking changes in 2.0? See discussion on 5498605efafcacb6091453b3f2be7d934aedec75. If so, I propose a maintenance branch for 1.x (1.8, with the fixes in the commit) so that users won't have to deal with breaking changes just to get a build for recent versions/LTSs.

**Comment by slpopejoy** [comment]
Yeah ... just tried updating my GHC 7.10.x project and deps are a nightmare (can't get the new Eq1/Show1s to work. Using stack LTS 6.x). I will put together a PR for a branch to release 1.8 with recent-enough deps.

**Comment by cartazio** [comment]
The eq1 etc stuff works differently in 8.0 land, so there's no real way to
side step that.

**Comment by RyanGlScott** [comment]
At long last, [`bound-2`](http://hackage.haskell.org/package/bound-2) has been uploaded to Hackage.
