### ISSUE TITLE
instance MFunctor (Scope b)

### ISSUE THREAD

**Issue by ollef** [ekmett/bound#52]
`Scope` can be an instance of [`MFunctor` from mmorph](https://hackage.haskell.org/package/mmorph-1.0.9/docs/Control-Monad-Morph.html#t:MFunctor):

```haskell
instance MFunctor (Scope b) where
    hoist = hoistScope
```

I'm not sure how you feel about incurring another dependency, but it might be worth considering.

**Comment by phadej** [comment]
I'm ok with this. Could you make a PR (don't forget the `Bound.Scope.Simple`)?
