### ISSUE TITLE
bound-2 won't build with current `stack`

### ISSUE THREAD

**Issue by ThreeFx** [ekmett/bound#62]
[1 of 2] Compiling Main             ( /tmp/stack11223/bound-2/Setup.lhs,
    /tmp/stack11223/bound-2/.stack-work/dist/x86_64-linux-ncurses6/Cabal-
    1.24.2.0/setup/Main.o )
    
    /tmp/stack11223/bound-2/Setup.lhs:24:1: error:
        Failed to load interface for ‘Warning’
        Use -v to see a list of the files searched for.

I checked the source tarball and it seems like `Warning.hs` is missing entirely.

Edward mentioned to tag you @phadej to fix it.

**Comment by phadej** [comment]
What version is "current stack"?

**Comment by ThreeFx** [comment]
`lts-8.17` and/or `nightly-2017-06-10`

Also, it's pulled in as an `extra-dep` if that makes any difference since stackage only has `bound-1.something`

**Comment by phadej** [comment]
I see. We forgot to include `Warning` module into other-sources. But we have better way to do this.

**Comment by ThreeFx** [comment]
Thanks!
