### ISSUE TITLE
Trouble implementing `Monad` instance when scoping more than one term

### ISSUE THREAD

**Issue by Ptival** [ekmett/bound#71]
Sorry to post this as a GitHub issue, this might not be the best venue for such questions.

I used to have a type like:
```
data Term v
= Constructor (Scope N Term v)
```
which easily satisfied all the good things we could care about (like Monad).

Now, I would like to have a pair of two terms sharing the exact same scope. My initial approach is the following:
```
data Paired f v = Paired (f v, f v)

data Term v
= Constructor (Scope N (Paired Term) v)
```
Unfortunately, the `Paired` type is not a `Monad`, because it makes no sense to substitute variables for pairs of terms. It is, however, an instance of `Bound`, as it supports `Paired f a -> (a -> f c) -> Paired f c`. I cannot figure out how to write the `Monad` instance for `Term` though.

The easy way out is to instead define:
```
data Term v
= Constructor (Scope N f v) (Scope N f v)
```
and manually enforce that the scopes are the same.

But I wonder whether the former approach is doomed, or whether I'm just missing something.

Do all the `Scope` methods that have a requirement `Monad f` really need this requirement, or is it required because it is expected that `f` would be a `Monad`?

**Comment by phadej** [comment]
@Ptival I recently had the very similar problem and wrote.

https://gist.github.com/phadej/a629bf5b304764118cd4a657f74b5669 - I made only combinators I needed though.

The combinators then need `Bound t` and `Monad f` (which is /less/ then `Monad (t f)`), which you can satisfy (you have `t = Paired`, `f = Term`)

Hopefully this helps.

**Comment by Ptival** [comment]
Great! I ended up using your solution. I also needed a couple extras, here they are:

```
instance (Bound t, Eq n, Eq1 (t f), Monad f) => Eq1 (ScopeT n t f) where
  liftEq eqVar m n = liftEq (liftEq eqVar) (fromScopeT m) (fromScopeT n)

instance (Bound t, Eq a, Eq n, Eq1 (t f), Monad f) => Eq (ScopeT n t f a) where
  (==) = eq1

hoistScopeT :: (Functor (t f)) =>
  (forall x. t f x -> t g x) ->
  (forall x. f x -> g x) ->
  ScopeT b t f a -> ScopeT b t g a
hoistScopeT t f (ScopeT b) = ScopeT $ t $ (f <$>) <$> b
```

Two questions:

- Is it okay for me to use your code snippet in my project? (it's open source, under MIT license)

- Should we consider adding your `ScopeT` to `bound`?

**Comment by phadej** [comment]
1. yes it is
2. I guess. I think the need arises when you have terms of different sorts, and you don't want shovel them into the same data type. What is your need to not do

```haskell
data Term v
    = Constructor (Scope N Term v)
    | Paired (Term v) (Term v)
```

In my case, I did a language with a bidirectional type checking, so I have inferrable terms and checkable terms. I only ever substitute inferrable terms. I guess you have something similar, you don't substitute pair of terms into a term?

**Comment by Ptival** [comment]
My use case is to implement a language with a `Match` or `Case` construct that has guards:
```
foo (C a b c) | expr1 a b c = expr2 a b c
```
So, each branch has an optional guard and a body, which are both scoped by things introduced by the pattern. So I initially wanted:
```
data GuardAndBody v =
  { branchGuard :: Maybe (Term v)
  , branchBody :: Term v
  }
```
And this is, in no sense, a valid term.

**Comment by phadej** [comment]
```haskell
data GuardAndBody f v
  { branchGuard :: Maybe (f v)
  , branchGuard :: f v
  }
```

i assume?

I see, it's a good example

**Comment by Ptival** [comment]
Oh yes, that's what I meant!

**Comment by phadej** [comment]
I made a WIP-PR, ping @sgraf812 and @Ptival  https://github.com/ekmett/bound/pull/73
