### ISSUE TITLE
`Imperative` example fails to compile

### ISSUE THREAD

**Issue by b-mehta** [ekmett/bound#75]
In particular, a file containing:
```
{-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable, RankNTypes, ScopedTypeVariables #-}
module Lib where

import Bound

data Prog operand a
  = Ret (operand a)
  | Add (operand a) (operand a)
        (Prog (Scope () operand) a)
  deriving (Eq,Ord,Show,Read,Functor,Foldable,Traversable)

pAbstract1 :: forall operand a. (Applicative operand, Monad operand, Eq a)
           => a
           -> Prog operand a
           -> Prog (Scope () operand) a
pAbstract1 = go abstract1
  where
    go :: forall o o' u. Eq u
       => (forall v. Eq v => v -> o v -> o' v)
       -> u -> Prog o u -> Prog o' u
    go f x (Ret o)        = Ret (f x o)
    go f x (Add o1 o2 cc) = Add (f x o1) (f x o2)
                          $ go f' x cc
      where
        f' :: forall v. Eq v => v -> Scope () o v -> Scope () o' v
        f' v = Scope . f (F v) . unscope
```
gives the following error:
```
    • Occurs check: cannot construct the infinite type: v ~ o v
      Expected type: Scope () o v -> o (Var () v)
        Actual type: Scope () o v -> o (Var () (o v))
    • In the second argument of ‘(.)’, namely ‘unscope’
      In the second argument of ‘(.)’, namely ‘f (F v) . unscope’
      In the expression: Scope . f (F v) . unscope
   |
44 |         f' v = Scope . f (F v) . unscope
   |
```
despite being in the `examples/` folder of this repo.

**Comment by RyanGlScott** [comment]
This isn't quite the same as the code in `examples/Imperative.hs`. You've changed the imports a bit: while `examples/Imperative.hs` imports `Bound.Scope.Simple`, you're importing `Bound`, which re-exports things from `Bound.Scope`. Note that `Bound.Scope` and `Bound.Scope.Simple` present an almost identical API, the exact types are a little bit different. In particular, compare [`Bound.Scope`'s `unscope` function](http://hackage.haskell.org/package/bound-2.0.1/docs/Bound-Scope.html#v:unscope) to [`Bound.Scope.Simple`'s `unscope` function](http://hackage.haskell.org/package/bound-2.0.1/docs/Bound-Scope-Simple.html#v:unscope). The differences between these two types are what is causing the type error you're seeing.

**Comment by phadej** [comment]
We could replace `unscope` with `fromScope`, which would make the file work with either `Scope`.

**Comment by b-mehta** [comment]
Ahh I didn't notice that difference. Thanks!
