### ISSUE TITLE
Should there be liftScope and should we remove MonadTrans Scope

### ISSUE THREAD

**Issue by phadej** [ekmett/bound#77]
Let's assume that `transformers` will start to use QuantifiedConstraints tomorrow

```haskell
class (forall m. Monad m => Monad (t m)) => MonadTrans t where ...
```

Then we would be screwed. Should we take the bullet already today?

**Comment by cartazio** [comment]
this sounds like a really good / important design concern ... and also a possible form of breakage that the associated change to base might have on a lot of libraries! 

(also how would doing this change in bound impact/ break any on hackage users of bound? i imagine that for non hackage ones, the impact is neglibable)

**Comment by RyanGlScott** [comment]
Forgive me for being slow, but why would we be screwed if `MonadTrans` gained that superclass? Aren't there already `instance Monad f => Monad (Scope f)` instances?

**Comment by cartazio** [comment]
you're right ... so would we just be dropping the trans lifting instance on our side? ... or what would the implication be? (perhaps i'm the one being slow here!)

**Comment by phadej** [comment]
@RyanGlScott oh sorry, you are right. For some reason I thought that `Scope` is not a `Monad`. But as it is, there are no problems.
