### ISSUE TITLE
The `template-haskell` `cabal` flag doesn't do anything

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/bound#85]
Despite having a `template-haskell` `cabal` flag seemingly for the purpose of allowing users to opt out of the `template-haskell` library dependency:

https://github.com/ekmett/bound/blob/6d2ca741743ecfdd779a4f52dcfb45fbb6f9f200/bound.cabal#L107-L108

It turns out that `bound` _also_ depends on the `template-haskell` library unconditionally elsewhere in the file, defeating the point of having the `cabal` flag in the first place:

https://github.com/ekmett/bound/blob/6d2ca741743ecfdd779a4f52dcfb45fbb6f9f200/bound.cabal#L95

We should either:

1. Properly depend on the `template-haskell` library conditionally, or
2. Remove the `template-haskell` `cabal` flag altogether.

**Comment by RyanGlScott** [comment]
I stand corrected—the flag actually _does_ do something, as if the flag is disabled, the `Bound.TH` module will not export anything. See [here](https://github.com/ekmett/bound/blob/6d2ca741743ecfdd779a4f52dcfb45fbb6f9f200/src/Bound/TH.hs#L20). In this case, I think we should just go with option (1).

**Comment by phadej** [comment]
I'd say we should make `template-haskell` functionality unconditional and use `TemplateHaskellQuotes` in `TH` module. We don't really use TH itself, only provide TH-utilities.

**Comment by RyanGlScott** [comment]
I'm fine with either option. I'll merge #86 first regardless, if for no other reason than to fix the build before we make further changes.

**Comment by phadej** [comment]
Note that `th-abstraction` depends on TH anyway. But not using th in this package may indeed speed up compilation.

The

```diff
diff --git a/bound.cabal b/bound.cabal
index ef98316..60f8cb0 100644
--- a/bound.cabal
+++ b/bound.cabal
@@ -56,14 +56,6 @@ tested-with:
   GHC==8.10.4,
   GHC==9.0.1
 
-flag template-haskell
-  description:
-    You can disable the use of the `template-haskell` package using `-f-template-haskell`.
-    .
-    Disabling this is an unsupported configuration, but it may be useful for accelerating builds in sandboxes for expert users.
-  default: True
-  manual: True
-
 source-repository head
   type: git
   location: git://github.com/ekmett/bound.git
@@ -92,6 +84,7 @@ library
     mmorph           >= 1.0     && < 1.3,
     deepseq          >= 1.1     && < 1.5,
     profunctors      >= 3.3     && < 6,
+    template-haskell >= 2.7     && < 3.0,
     th-abstraction   >= 0.4     && < 0.5,
     transformers     >= 0.2     && < 0.6,
     transformers-compat >= 0.5  && < 1
@@ -103,8 +96,6 @@ library
   if impl(ghc >=7.4 && < 7.6)
     build-depends: ghc-prim
 
-  if flag(template-haskell) && impl(ghc)
-    build-depends: template-haskell >= 2.7 && < 3.0
 
 test-suite Simple
   type: exitcode-stdio-1.0
diff --git a/cabal.haskell-ci b/cabal.haskell-ci
index b13e394..bc06e9e 100644
--- a/cabal.haskell-ci
+++ b/cabal.haskell-ci
@@ -4,6 +4,3 @@ unconstrained:          False
 -- irc-channels:           irc.freenode.org#haskell-lens
 irc-if-in-origin-repo:  True
 docspec:                True
-
-constraint-set no-template-haskell
-  constraints: bound -template-haskell
diff --git a/src/Bound/TH.hs b/src/Bound/TH.hs
index b90b887..871fab9 100644
--- a/src/Bound/TH.hs
+++ b/src/Bound/TH.hs
@@ -1,6 +1,10 @@
 {-# LANGUAGE CPP             #-}
-{-# LANGUAGE TemplateHaskell #-}
 {-# LANGUAGE PatternGuards   #-}
+#if __GLASGOW_HASKELL__ >=800
+{-# LANGUAGE TemplateHaskellQuotes #-}
+#else
+{-# LANGUAGE TemplateHaskell #-}
+#endif
 
 -----------------------------------------------------------------------------
 -- |
```

almost works. But there is one (declaration) splice in Bound.TH module which is unfortunate. That have to be rewritten manually.

**Comment by RyanGlScott** [comment]
I think we can put this to rest now that #88 has been merged.
